#
# --- ZSH Config
#

# --- aliases

# gocryptfs
alias vault-important="gocryptfs ${HOME}/.Vaults/Important ${HOME}/Vaults/Important"
alias vault-recovery="gocryptfs ${HOME}/.Vaults/Recovery ${HOME}/Vaults/Recovery"

# --- plugins

# use antigen
source /Users/jamie.king/.antigen.zsh

# oh-my-zsh
antigen use oh-my-zsh

# unix plugins
antigen bundle sudo

# programming bundles
antigen bundle git

antigen bundle nvm
antigen bundle npm
antigen bundle yarn

antigen bundle python
antigen bundle pyenv
antigen bundle virtualenv

antigen bundle vscode

# zsh plugins
antigen bundle zsh-users/zsh-syntax-highlighting
#antigen bundle zsh-users/zsh-autosuggestions

# theme
antigen theme gnzh

# apply settings
antigen apply

# --- environmental variables

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"


# --- misc ZSH things

# virtualenv_info
function virtualenv_info {
    [ $VIRTUAL_ENV ] && echo '('`basename $VIRTUAL_ENV`') '
}


# --- misc program things

# item2 integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# pyenv
eval "$(pyenv init -)"
